export const githubSyncConfig = {
  username: "kauankelvin7",
  revalidateSeconds: 60 * 60,
  maxAutoProjects: 6,
  maxStacks: 14,
  maxContributions: 6,
  curatedRepositories: new Set([
    "Leve",
    "Automacao-Clinica-Odontologica",
    "Omni",
    "Cinesia",
    "socplug-fix",
  ]),
  featuredContributionNumbers: new Set([16135, 16162]),
  ignoredRepositories: new Set(["portifolio-dev", "portifolio_developer"]),
  ignoredTopics: new Set(["portfolio-ignore", "archive", "template", "learning-only"]),
  preferredTopics: new Set([
    "portfolio",
    "featured",
    "java",
    "spring-boot",
    "python",
    "automation",
    "react",
    "typescript",
    "pwa",
    "firebase",
    "postgresql",
  ]),
} as const;

export const stackAliases: Record<string, string> = {
  javascript: "JavaScript",
  typescript: "TypeScript",
  java: "Java",
  python: "Python",
  html: "HTML",
  css: "CSS",
  shell: "Shell",
  react: "React",
  nextjs: "Next.js",
  "next-js": "Next.js",
  vite: "Vite",
  tailwind: "Tailwind CSS",
  "tailwind-css": "Tailwind CSS",
  firebase: "Firebase",
  postgresql: "PostgreSQL",
  postgres: "PostgreSQL",
  mysql: "MySQL",
  docker: "Docker",
  selenium: "Selenium",
  spring: "Spring Boot",
  "spring-boot": "Spring Boot",
  node: "Node.js",
  nodejs: "Node.js",
  express: "Express",
  pwa: "PWA",
  git: "Git",
  linux: "Linux",
};
